Add tests for Remora.Discord.Caching
Remora/Remora.Discord pull request #246
Opened 2022-10-22 00:40 UTC by uwx

Adds unit tests for basic functionality of the cache system. Note that these tests **will not pass** as the cache configuration functionality is broken, which is fixed by #245.

2022-10-22 11:21 UTC, MazeXP requested changes

2022-10-22 11:21 UTC, MazeXP commented on Tests/Remora.Discord.Caching.Tests/CacheTests.cs
> +            .CreateScope().ServiceProvider;
I would either move this to a fixture or into its own method as it is always the same for every test.

2022-10-25 16:34 UTC, Nihlus commented
If these tests are part of #245's functionality, they should probably be part of that PR as well.

2022-10-25 23:48 UTC, uwx commented
> If these tests are part of #245's functionality, they should probably be part of that PR as well.

Technically not, they are just general regression tests for caching that were missing from the library. Even if that one doesn't get merged, this one should still be.

2022-12-23 18:38 UTC, MazeXP requested changes

2022-12-23 18:38 UTC, MazeXP commented on Tests/Remora.Discord.Caching.Tests/ResultAssert.cs
> +}
Reference `Remora.Discord.Tests` project for `ResultAssert`.

2022-12-23 18:38 UTC, MazeXP commented on Tests/Remora.Discord.Caching.Tests/Remora.Discord.Caching.Tests.csproj
> +        <ProjectReference Include="..\..\Backend\Remora.Discord.API\Remora.Discord.API.csproj" />
```suggestion
```
Obsolete reference as it will be pulled by `Remora.Discord.Caching` transitively.

2022-12-23 18:38 UTC, MazeXP commented on Tests/Remora.Discord.Caching.Tests/Remora.Discord.Caching.Tests.csproj
> +        <ProjectReference Include="..\..\Backend\Remora.Discord.Unstable\Remora.Discord.Unstable.csproj" />
```suggestion
```
As nothing from `Remora.Discord.Unstable` is being used, it should be removed.

2022-12-24 16:25 UTC, merged