feat: implement abstraction level for feedback service
Remora/Remora.Discord pull request #290
Opened 2023-03-19 17:54 UTC by Inerska

This PR implements an higher abstraction level for FeedbackService, it will allow people to mock FeedbackService easier.

2023-03-19 17:55 UTC, VelvetThePanda reviewed
LGTM

2023-03-19 17:55 UTC, VelvetThePanda commented on Remora.Discord.Commands/Feedback/Services/FeedbackService.cs
Documentation on this service should be changed to `/// <inheritdoc>`

2023-03-19 17:56 UTC, Inerska commented on Remora.Discord.Commands/Feedback/Services/FeedbackService.cs
Fixed with the new commit.

2023-03-19 18:04 UTC, mdabrarhassan commented
https://github.com/Remora/Remora.Discord/blob/main/Remora.Discord.Commands/Extensions/ServiceCollectionExtensions.cs#L249

Should the abstraction not also be registered here?

2023-03-19 18:08 UTC, Nihlus requested changes
Looks good, mostly issues with formatting :)

I would like you to modify the service registration as well so that end users can request the interface instead of the concrete type. The samples should probably be adjusted to do so as well.

2023-03-19 18:08 UTC, Nihlus commented on Remora.Discord.Commands/Feedback/Services/IFeedbackService.cs
> +    Task<Result<IReadOnlyList<IMessage>>> SendContextualContentAsync(
Formatting. The opening brace should be placed on a new line if you can't fit it all on the same line, same way you'd handle { and }.

Check the other methods for this as well.

2023-03-19 18:08 UTC, Nihlus commented on Remora.Discord.Commands/Feedback/Services/IFeedbackService.cs
> +///     Handles sending formatted messages to the users.
Do not indent text within documentation comments.

Check the other documentation comments as well.

2023-03-19 18:08 UTC, Nihlus commented on Remora.Discord.Commands/Feedback/Services/FeedbackService.cs
> +    : IFeedbackService
This should be on the same line as the class declaration unless required.

2023-03-19 18:08 UTC, Nihlus commented on Remora.Discord.Commands/Feedback/Services/FeedbackService.cs
> +/// <inheritdoc />
Replace the documentation comments on the interface-implemented methods with inheritdoc as well.

2023-03-19 18:08 UTC, Nihlus commented on Remora.Discord.Commands/Feedback/Services/IFeedbackService.cs
> +    ///     Checks if the current context is an InteractionContext.
Reuse the existing documentation on FeedbackService where possible. This goes for all the methods.

2023-03-19 18:48 UTC, MazeXP commented
> https://github.com/Remora/Remora.Discord/blob/main/Remora.Discord.Commands/Extensions/ServiceCollectionExtensions.cs#L249
> 
> Should the abstraction not also be registered here?

You are totally right on this one!

2023-03-19 19:24 UTC, MazeXP requested changes

2023-03-19 19:24 UTC, MazeXP commented on Remora.Discord.Commands/Extensions/ServiceCollectionExtensions.cs
> +        serviceCollection.TryAddScoped<IFeedbackService, FeedbackService>();
```suggestion
        serviceCollection.TryAddScoped<FeedbackService>();
        serviceCollection.TryAddScoped<IFeedbackService>(s => s.GetRequiredService<FeedbackService>());
```
To keep backwards compatibility.

2023-03-20 20:40 UTC, Nihlus approved these changes

2023-03-20 20:41 UTC, merged