Fix/user apps
Remora/Remora.Discord pull request #336
Opened 2024-04-29 19:26 UTC by VelvetToroyashi

2024-05-02 17:54 UTC, Nihlus commented
You're still missing test payloads for the added entities and tests for those.

2024-05-02 17:57 UTC, VelvetToroyashi commented
For interaction objects? Or the application object

2024-05-02 18:00 UTC, Nihlus commented
The JSON payloads under test haven't been updated for existing entities (IApplicationCommand) and no new JSON payloads have been added for new types (like IMessageInteractionMetadata). Check your changed and added entities from both this PR and #327.

2024-05-11 02:01 UTC, MazeXP requested changes
LGTM, just some small things. :)

2024-05-11 02:04 UTC, VelvetToroyashi commented on Backend/Remora.Discord.API.Abstractions/API/Objects/Interactions/IMessageInteractionMetadata.cs
> +    Optional<string> Name { get; }
Was added between the PR being opened, and Shay marking it as unreleased https://github.com/discord/discord-api-docs/pull/6734

2024-05-11 02:07 UTC, VelvetToroyashi commented on Backend/Remora.Discord.API/Json/Converters/Internal/EnumKeyDictionaryConverterFactory.cs
> +public class EnumKeyDictionaryConverterFactory : JsonConverterFactory
The semantics on this class are a little scuffed; technically a stringified integer, so perhaps it'd be better to clarify in the documentation?

2024-05-11 02:08 UTC, MazeXP commented on Backend/Remora.Discord.API.Abstractions/API/Objects/Interactions/IMessageInteractionMetadata.cs
> +    Optional<string> Name { get; }
Alright, Jax must decide on it

2024-05-11 02:12 UTC, MazeXP commented on Backend/Remora.Discord.API/Json/Converters/Internal/EnumKeyDictionaryConverterFactory.cs
> +public class EnumKeyDictionaryConverterFactory : JsonConverterFactory
Well, in JSON terms a key of an object is always a string

2024-05-11 11:25 UTC, Nihlus commented on Backend/Remora.Discord.API.Abstractions/API/Objects/Interactions/IMessageInteractionMetadata.cs
> +    Optional<string> Name { get; }
If it's not documented yet, don't implement it. Especially not when Discord themselves say "this is unstable and intentionally not documented".

2024-05-17 18:34 UTC, Nihlus commented
You've got a few alerts remaining along with some merge conflicts that came in as part of polls - other than that, things seem ready to go.

2024-05-17 19:09 UTC, VelvetToroyashi commented
@Nihlus should be good to go now

2024-05-17 19:38 UTC, merged