Implement Forwarding
Remora/Remora.Discord pull request #347
Opened 2024-12-08 09:57 UTC by vicr123

This PR adds data structures to support forwarding

2025-01-02 04:30 UTC, VelvetToroyashi approved these changes

2025-01-02 10:32 UTC, Nihlus commented on Tests/Remora.Discord.Tests/Samples/Gateway/Events/MESSAGE_CREATE/MESSAGE_CREATE.nulls.json
> +    "message_snapshots": null,
This field is optional, not nullable.

2025-01-02 10:37 UTC, Nihlus requested changes

2025-01-02 10:37 UTC, Nihlus commented on Tests/Remora.Discord.Tests/Samples/Objects/MESSAGE/MESSAGE.nulls.json
> +  "message_snapshots": null,
This field is optional, not nullable.

2025-01-02 10:37 UTC, Nihlus commented on Tests/Remora.Discord.Tests/Samples/Objects/MESSAGE_REFERENCE/MESSAGE_REFERENCE.json
> +  "type": 0,
This field is optional and is missing test data.

2025-01-02 10:37 UTC, Nihlus commented on Tests/Remora.Discord.Tests/Samples/Objects/MESSAGE_SNAPSHOT/MESSAGE_SNAPSHOT.optionals.json
> +  "message": {
MessageSnapshot contains no optional fields - this file is redundant and can be deleted.

2025-01-02 10:37 UTC, Nihlus commented on Tests/Remora.Discord.Tests/Samples/Objects/MESSAGE_SNAPSHOT/MESSAGE_SNAPSHOT.json
> +  "message": {
Please add a separate file where the partial message is an empty object (`MESSAGE_SNAPSHOT.partials.json`) - we want to cover both a populated and unpopulated message path.

2025-01-06 08:55 UTC, vicr123 commented on Tests/Remora.Discord.Tests/Samples/Objects/MESSAGE_REFERENCE/MESSAGE_REFERENCE.json
> +  "type": 0,
Hmm, I'm not sure what you'd like me to add here specifically :(

2025-02-06 19:29 UTC, Nihlus commented on Tests/Remora.Discord.Tests/Samples/Objects/MESSAGE_REFERENCE/MESSAGE_REFERENCE.json
> +  "type": 0,
I'd like you to add a MESSAGE_REFERENCE.optionals.json file where all optional fields are omitted from the JSON payload. The goal of the *.optional.json files are to test that the data still serializes and deserializes properly when optional fields are omitted from the value.

2025-02-12 16:11 UTC, Nihlus commented
I'll pull this down and add the missing data myself to get it into the upcoming release. Thanks for your contribution!

2025-02-12 16:11 UTC, merged

2025-02-12 17:28 UTC, vicr123 commented
Thanks! Apologies I've been a bit busy so haven't had the time to look at what you've written